name: Delete old workflow runs

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 0 * * 0"   # optional weekly cleanup

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs (keep last 5)
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow = "Unity WebGL CI"; // workflow name or filename
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflow,
              per_page: 100
            });
            const oldRuns = runs.data.workflow_runs.slice(5); // keep latest 5
            for (const run of oldRuns) {
              console.log(`🗑️ Deleting run #${run.id} (${run.name})`);
              await github.rest.actions.deleteWorkflowRun({
                owner,
                repo,
                run_id: run.id
              });
            }
            console.log(`✅ Deleted ${oldRuns.length} old runs.`);
