name: Unity License Check

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify UNITY_LICENSE is present
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          if [ -z "$UNITY_LICENSE" ]; then
            echo "❌ UNITY_LICENSE secret is not set."
            exit 1
          fi
          echo "::add-mask::$UNITY_LICENSE"
          echo "✅ UNITY_LICENSE secret is set (value masked)."
