name: Unity License Check

on:
  workflow_dispatch: # run manually from GitHub UI

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Unity in batch mode
        run: |
          set -e
          docker run --rm \
            -e UNITY_LICENSE="${{ secrets.UNITY_LICENSE }}" \
            ghcr.io/game-ci/unity-editor:2022.3.48f1-linux-il2cpp-3 \
            -batchmode -nographics -quit -logFile - \
          | tee unity_log.txt

      - name: Check license status in log
        run: |
          if grep -E "License type:|ULS|LICENSE SYSTEM" unity_log.txt >/dev/null; then
            echo "✅ Unity license detected and active."
          else
            echo "❌ No valid license detected — check UNITY_LICENSE secret." >&2
            exit 1
          fi
