name: Unity License Check

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  activate-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: fail fast if secret is missing
      - name: Verify UNITY_LICENSE is present
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          if [ -z "$UNITY_LICENSE" ]; then
            echo "❌ UNITY_LICENSE secret is not set."
            exit 1
          fi
          echo "::add-mask::$UNITY_LICENSE"

      # Activate Unity via GameCI
      - name: Activate Unity
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: 2021.3.41f1            # <- set your exact version
          activationMode: server               # default; fine to omit
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
