name: Unity WebGL CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-webgl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Reclaim disk space on the runner before pulling the Unity Docker image
      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false   # keep Docker engine; we'll prune images next
          swap-storage: true
      - name: Prune Docker (images/volumes)
        run: |
          docker system prune -af || true
          docker volume prune -f || true
      - name: Show free space
        run: df -h

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-WebGL-${{ hashFiles('Packages/manifest.json') }}
          restore-keys: |
            Library-WebGL-

      # Verify required secrets are present
      - name: Verify Unity secrets
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
        run: |
          for var in UNITY_EMAIL UNITY_PASSWORD UNITY_LICENSE; do
            if [ -z "${!var}" ]; then
              echo "❌ Missing $var"
              exit 1
            fi
            echo "::add-mask::${!var}"
          done
          echo "✅ Unity secrets present (masked)."

      - name: Build WebGL (Unity 6 Build Profile)
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 6000.0.60f1
          targetPlatform: WebGL            # kept for artifact path naming
          buildName: WebGLBuild
          buildProfile: "Assets/Settings/Build Profiles/WebBuild.asset"
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGL
