name: Unity WebGL CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-webgl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-WebGL-${{ runner.os }}-6000.0.60f1-${{ hashFiles('Packages/manifest.json', 'Packages/packages-lock.json') }}
          restore-keys: |
            Library-WebGL-${{ runner.os }}-6000.0.60f1-
            Library-WebGL-

      # Verify required secrets are present
      - name: Verify Unity secrets
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
        run: |
          for var in UNITY_EMAIL UNITY_PASSWORD UNITY_LICENSE; do
            if [ -z "${!var}" ]; then
              echo "❌ Missing $var"
              exit 1
            fi
            echo "::add-mask::${!var}"
          done
          echo "✅ Unity secrets present (masked)."

      - name: Build WebGL (explicit build method)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
          # Optional hardening to reduce noisy UPM/Accelerator messages:
          UNITY_ACCELERATOR_ENDPOINT: ""
          UPM_DISABLE_DEPENDENCY_RESOLVER_SATISFIABILITY: true
        with:
          projectPath: .
          unityVersion: 6000.0.60f1
          targetPlatform: WebGL
          buildMethod: UnityBuilderAction.Builder.BuildProject
          customParameters: >
            -buildName WebGLBuild
            -buildPath build/WebGL

      - name: Upload artifact (for debugging/download)
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL

      # ---- GitHub Pages deploy ----
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGL

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
